name: routine_mate
description: 매일 작은 실천을 통해 큰 변화를 만드는 가장 심플한 습관 트래커
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Database
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.3

  # Utilities
  uuid: ^4.4.0
  intl: ^0.19.0

  # Home Widget (향후 추가)
  # home_widget: ^0.5.0

  # Ads (향후 추가)
  # google_mobile_ads: ^5.0.0

  # Analytics (향후 추가)
  # firebase_core: ^2.27.0
  # firebase_analytics: ^10.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  # Assets 설정 (향후 추가)
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # 폰트 설정 (향후 추가)
  # fonts:
  #   - family: Pretendard
  #     fonts:
  #       - asset: assets/fonts/Pretendard-Regular.ttf
  #       - asset: assets/fonts/Pretendard-Bold.ttf
  #         weight: 700